[versions]
agp = "9.3.1"
activity = "1.13.0"
annotation = "1.9.1"
appcompat = "1.7.1"
cardview = "1.0.0"
colorpicker = "1.1.0"
commonsText = "1.15.0"
concurrentFutures = "1.3.0"
constraintlayout = "2.2.1"
coreSplashscreen = "1.2.0"
desugar_jdk_libs = "2.1.5"
fragmentKtx = "1.8.9"
gson = "2.14.0"
hiltAndroid = "2.60.1"
hiltAndroidCompiler = "2.60.1"
javapoet = "1.13.0"
localbroadcastmanager = "1.1.0"
lottie = "6.7.1"
libsuVersion = "6.0.0"
android-material = "1.14.0"
markdownviewAndroid = "1.1.1" #keep this version. higher versions are compose
navigationFragmentKtx = "2.9.8"
objenesis = "3.5"
ntpClient = "0.0.1-alpha11"
persianDateTime = "4.2.1"
playServicesBase = "18.10.0"
playServicesMlkitSubjectSegmentation = "16.0.0-beta1"
prdownloader = "1.0.2"
#noinspection NewerVersionAvailable
pytorch_android_torchvision_lite = "1.13.1"
recyclerview = "1.4.0"
preferenceKtx = "1.2.1"
remotepreferences = "0.8"
swiperefreshlayout = "1.2.0"
transition = "1.7.0"
composeBom = "2026.06.01"
workRuntime = "2.11.2"
kotlin = "2.4.10"
ksp = "2.3.10"
hilt = "2.60.1"
lsposed-api = "102.0.0"
lsposed-service = "102.0.0"
dexkit = "2.2.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-transition = { module = "androidx.transition:transition", version.ref = "transition" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-geometry = { module = "androidx.compose.ui:ui-geometry" }
androidx-work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
colorpicker = { module = "com.jaredrummler:colorpicker", version.ref = "colorpicker" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
libsuCore = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsuVersion" }
libsuNIO = { module = "com.github.topjohnwu.libsu:nio", version.ref = "libsuVersion" }
libsuService = { module = "com.github.topjohnwu.libsu:service", version.ref = "libsuVersion" }
markdownview-android = { module = "com.github.mukeshsolanki:MarkdownView-Android", version.ref = "markdownviewAndroid" }
objenesis = { group = "org.objenesis", name = "objenesis", version.ref = "objenesis" }
ntpClient = { group = "com.lyft.kronos", name = "kronos-android", version.ref = "ntpClient" }
persian-date-time = { module = "com.github.mfathi91:persian-date-time", version.ref = "persianDateTime" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
play-services-mlkit-subject-segmentation = { module = "com.google.android.gms:play-services-mlkit-subject-segmentation", version.ref = "playServicesMlkitSubjectSegmentation" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
prdownloader = { module = "com.github.amitshekhariitbhu:PRDownloader", version.ref = "prdownloader" }
pytorch_android_lite = { module = "org.pytorch:pytorch_android_lite", version.ref = "pytorch_android_torchvision_lite" }
pytorch_android_torchvision_lite = { module = "org.pytorch:pytorch_android_torchvision_lite", version.ref = "pytorch_android_torchvision_lite" }
remotepreferences = { module = "com.crossbowffs.remotepreferences:remotepreferences", version.ref = "remotepreferences" }
lsposed-api = { module = "io.github.libxposed:api", version.ref = "lsposed-api" }
lsposed-service = { module = "io.github.libxposed:service", version.ref = "lsposed-service" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }